### ISSUE TITLE
Support for Voter Registration Lookups

### ISSUE THREAD

**Issue by JDziurlaj** [usnistgov/VoterRecordsInterchange#7]
# Voter Lookup Proposal

A consequence of the streamlined structure proposed in issue #6 (Ballot Requests) is voter information is now independent of a particular form used by a voter . A major advantage of this revised structure is that the same **Voter** class can be used in different contexts, such as *registration*, *ballot request* or **lookup**. 

Prior versions of VRI did not explicitly support a lookup use-case. It was assumed that the response to such a VRI request would be in an implementation dependent format.

# Proposed Changes

Add a new **VoterRecordsResponse** subtype, **VoterRecords**. Each VoterRecords object may contain zero or more **VoterRecord** instances. This structure is to handle a situation where a voter has multiple records, as well as where the lookup whose criteria was insufficiently precise to return a single voter. 
**VoterRecord** is a subtype of **Voter** with additional attributes to convey informational normally stored in a voter registration system, as:

- Districts that voter belongs (e.g. congressional districts, city wards, etc.)
- Locality of the voter
- Polling Location for the Voter
- Election Administration for the Voter
- Voter participation history

Note: There is no voter status. It is assumed any record that comes back will be an eligible voter.

**Comment by monicachilders** [comment]
Re: "There is no voter status. It is assumed any record that comes back will be an eligible voter." 

Is there any flexibility here? Voter reg systems have multiple statuses for these records (versions of active, pending, inactive, and declined are all common). It seems like it would be worth supporting these?

**Comment by JDziurlaj** [comment]
It does. But it's one of those things where we should probably have an enumeration for, and I'm not sure what those values should be. 'active' and 'inactive' come to mind, but 'inactive' means different things to different people. In Ohio 'inactive' meant "in an NVRA removal process, but still eligible to vote". I imagine other states will disagree. Thoughts, @pstenbjorn?

**Comment by JDziurlaj** [comment]
There are only three statuses in the proposed PR #9, `active`, and `confirmation`, and `other`
